script: npm run deploy
language: node_js
before_script:
- npm run build
env:
  global:
  - GH_REF: github.com/websemantics/phosphorjs-starter-kit.git
  - secure: DfSrJY8M48d28rrd4OKC0kPieRuQMUuRcX4F6u8xs+7qj7FDMzD2pqnoPupp6m9lkUHUx5YZgNxz+QakqHHBfPmxCLfAJ2zXPX7z9RTGStxTcCgcHTZxqWySN6oOfx6u+1054oSoM0GlwGOJkibHcSRbNthX1NTeigw7gJagrly+zTiomfr8VzkXPXj1NU1TNI+m5aVQvSaCYOTPZnbVXH1dhESvBgcWaK2+45VPRkuV8E3J6MBsag3E3jl3pw0lzBHQtyCEdDd19KtzapsoYIqaJovSb8Nc6ZfjxXDgDZRt0P1/hPGDCW5jVxZwt+4UriCmKOiFLwVhFfGM5BRrYgMR/EKc1elfeAdPt/JY1dVT143i8FuArKRqvLxLzQK9vUsWouIWRGMgr6UBpAXL7Go5r0xWYLUJOcS+cMs1DbDbevF8ac4dziEmEU+JfRI8GKc0N+jBnOZdk5Ny8kYlLM8/mQqjZv4BITpNuxy6/FolT78giKHDxUPotMx765ik6yFbMv0o7bv5QM4jCF8MB2DtjmXrf02eLWvDrjbjRfGZ7F1KVlWiV0+xlHuoJpQMTV0lGtQEn2m+c1q0hY4llZF2dnjZCAR8dyzQM7BOSnOwUYymCiBV7l7UB4gHyvtSITq7Y04PSJvPn469NmDx6qQqRi0HsCHhhTx9XpaOUho=
